# Python Library **Numpy** Notebook

### Why Should We Use **Numpy** instead of **List**?

In [ ]:
import numpy as np
import time
import sys

l = range(1000)
print(l)
print(sys.getsizeof(1)*len(l))

a = np.arange(1000)
print(a.size*a.itemsize)

size= 100000
l1= range(size)
l2= np.arange(size)

t1= time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python took: ", (time.time()-t1)*1000)

t1= time.time()
result = l1+l2
print("numpy took: ", (time.time()-t1)*1000)



## Python Numpy Basics


1.   List item
2.   List item



### The Basics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#get dimesion
b.ndim

2

In [ ]:
# Get Shape
b.shape

(2, 4)

In [ ]:
# Get data type
b.dtype

dtype('int64')

In [ ]:
a.dtype

dtype('int64')

In [ ]:
# Change data type
b = np.array([[1,2,3,4],[5,6,7,8]], dtype='int16')
b.dtype

dtype('int16')

In [ ]:
# Get size
a.itemsize

8

In [ ]:
b.itemsize

2

In [ ]:
# Get total element size
a.size

4

In [ ]:
b.size

8

In [ ]:
# Get total memory size
a.nbytes

32

In [ ]:
b.size*b.itemsize

16

In [ ]:
print(np.linspace(0,10,num=5))

### Accessing / changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Get specific element
a[:, 1]

array([2, 7])

In [ ]:
a[0, 2:4]

array([3, 4])

In [ ]:
# getting little tricky [startindex:endindex:stepsize]
a[:, 1:4:2]
a[:, 1:-1:2] #negitive indexing here we use

array([[2, 4],
       [7, 9]])

In [ ]:
# changing the elements
a[0, 2] = 99
print(a)
a[:, 4] = [17,19]
print(a)
a[:, 1] = [57,85]
print(a)

[[ 1  2 99  4 17]
 [ 6  7  8  9 19]]
[[ 1  2 99  4 17]
 [ 6  7  8  9 19]]
[[ 1 57 99  4 17]
 [ 6 85  8  9 19]]


In [ ]:
# 3d array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[1, 0, 1]

6

In [ ]:
b[:, 0] = [[11,12],[13,14]]
print(b)

[[[11 12]
  [ 3  4]]

 [[13 14]
  [ 7  8]]]


In [ ]:
a = np.array([[1,2,3,4,5,6,7,8,],[5,6,7,8,9,10,11,12],[12,13,14,15,16,17,18,19]])
a[[0,1,2],[4,5,6]]

array([ 5, 10, 18])

###Initialize different types of Arrays

In [ ]:
# All Zero's matrix
a= np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# All One's matrix
b = np.ones((2,3), dtype = 'int32')
print(b)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Any Number Array
a = np.full((3,3), 5, dtype = 'int16')
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# Matrix shape like a
b = np.full_like(a, 12)
print(b)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [ ]:
# a & b has same dtype here we can see
b.dtype

dtype('int16')

In [ ]:
# Generate Random Decimal Number
np.random.rand(4,2)

array([[0.35251471, 0.57441008],
       [0.71374826, 0.0175283 ],
       [0.53974229, 0.69956554],
       [0.72329505, 0.10398957]])

In [ ]:
# random Decimal like a shape
np.random.random_sample(a.shape)

array([[0.27704573, 0.05805485, 0.12537054],
       [0.428528  , 0.22208029, 0.94057632],
       [0.90433457, 0.92776005, 0.53187705]])

In [ ]:
# Random int number
np.random.randint(3, 9, size = (3,2))

array([[3, 3],
       [4, 8],
       [8, 5]])

In [ ]:
# Indentity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Repeat an Array
x = np.array([[5,6,7,8]])
y = np.repeat(x, 4, axis = 0)
print(y)

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# Challange 1
n = 5

x = np.ones([n,n])
print(x)
x[1:-1,1:-1] = 0
x[2,2]=9
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Copying an array
a = np.array([1,2,3])
print(a)
b = a.copy()
print(b)

## Don't Do this
c = a
print(c)
c[0] = 5
print(c)
print(a)


[1 2 3]
[1 2 3]
[1 2 3]
[5 2 3]
[5 2 3]


### Mathematics Basics

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
a + b

array([ 6,  8, 10, 12])

In [ ]:
a - b

array([-4, -4, -4, -4])

In [ ]:
a * b

array([ 5, 12, 21, 32])

In [ ]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
# take sin values
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [ ]:
a = np.ones((2,3),dtype ='int32')
print(a)
b = np.full((3,2),5)
print(b)

product = np.matmul(a,b)
print(product)


[[1 1 1]
 [1 1 1]]
[[5 5]
 [5 5]
 [5 5]]
[[15 15]
 [15 15]]


In [ ]:
# find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

# More Function
# Trace , Single vector decomposition, Eigenvalues, Matrix Norm, Inverse

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

### Statistics

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
np.min(x, axis= 1)

array([1, 5])

In [ ]:
np.max(x, axis= 1)

array([4, 8])

In [ ]:
np.sum(x, axis= 1)

array([10, 26])

### Reorganizing Array

In [ ]:
a =  np.array([[1,2,3],[4,5,6]])
print(a)
b= a.reshape(3,2)
#b = np.reshape(a, (3,2))
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Verticle Stacking (adding)
x = np.array([1,2,3])
y = np.array([4,5,6])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Horizontal Stacking
np.hstack((x,y))
x1= np.zeros((3,3))
print(x1)
print(x2)
x2= np.ones((3,3))
hstacking= np.hstack((x1,x2))
print(hstacking)
hstacking.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


(3, 6)

In [ ]:
#transform into 1 dimension array by using ravel
print(a.ravel())


###Miscellaneous

#### **Load data using Numpy**

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')